#
# Module manifest for module 'BOKUshell'
#
# Generated by: awegsche
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'BOKUshell.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0.1'

    # ID used to uniquely identify this module
    GUID              = 'f9996f7f-35ee-4879-b48f-de3da6ba8eb7'

    # Author of this module
    Author            = 'awegsche'

    # Company or vendor of this module
    CompanyName       = 'BOKU-IT CS/ITSG'

    # Copyright statement for this module
    Copyright         = '(c) 2023 awegsche. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'A powerful PowerShell module to interact with BOKU systems.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '4.0'



    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @( '*' )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @( '*' )

    # Variables to export from this module
    VariablesToExport = @( '*' )

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @( '*' )



    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('bokushell', 'boku', 'boku-it', 'api', 'core', 'windows', 'linux', 'trustee', 'quota', 'bokudrive')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/boku-it-cs/bokushell/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/boku-it-cs/bokushell'

            # A URL to an icon representing this module.
            IconUri      = 'https://i.imgur.com/plzJqJ0.png'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/boku-it-cs/bokushell/releases'

        } # End of PSData hashtable

    } # End of PrivateData hashtable



    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/boku-it-cs/bokushell/'

}